---
# update eeprom
- name: get current EEPROM config
  ansible.builtin.command:
    cmd: rpi-eeprom-config
  register: storage_current_eeprom
  changed_when: false

- name: create temp file for EEPROM config
  ansible.builtin.tempfile:
    state: file
    suffix: eeprom
  register: storage_eeprom_tempfile

- name: write current EEPROM config to temp file
  ansible.builtin.copy:
    content: "{{ storage_current_eeprom.stdout }}"
    dest: "{{ storage_eeprom_tempfile.path }}"
    mode: '0644'

- name: update BOOT_ORDER in temp file
  ansible.builtin.lineinfile:
    path: "{{ storage_eeprom_tempfile.path }}"
    regexp: '^BOOT_ORDER=.*'
    line: 'BOOT_ORDER={{ storage_eeprom_boot_order }}'

- name: apply updated EEPROM config
  ansible.builtin.command:
    cmd: rpi-eeprom-config --apply {{ storage_eeprom_tempfile.path }}
  changed_when: true

- name: remove EEPROM temp file
  ansible.builtin.file:
    path: "{{ storage_eeprom_tempfile.path }}"
    state: absent
